data_path:
  input: data\input\
  output: data\output\sample.csv

plot:
  x_label: dst_APPROXIMATE_DEBT
  y_label: dst_HH_INCOME
  z_label: dst_AGE
  cmap: viridis
  title: Leadscoring Cluster Plot

cluster:
  kmeans:
    n_clusters: 3
    kwargs:
      init: random
      max_iter: 300
      random_state: 0

  hierarchical:
    n_clusters: 3
    kwargs:
      linkage: ward

  dbscan:
    eps: 0.5
    min_samples: 5
    kwargs:
      metric: euclidean

columns:
  index:
    - prn
    - leadid
    - velocifyid
  label:
    - DEAL
  features:
    categorical:
      - lead_medium
      # - dst_SELF_EMPLOYED
      # - dst_GENDER
      # - dst_MARITAL_STATUS
    high_categorical:
      - dst_STATE
      # - dst_ETHNIC_GROUP
    numeric:
      - submitted_debt
      - pentius_debt        
      - dst_APPROXIMATE_DEBT
      - dst_ESTIMATED_TRADES
      - dst_AGE
      - dst_GENERAL_LOAN_TO_VALUE
      - dst_EST_HOME_VALUE
      - dst_NUM_KIDS
      - dst_NUM_ADULTS
      - dst_MR_AMT
      - dst_CREDIT_LINES
    ordinal:
      # - pentius_creditscore
      # - pentius_currentlydelinquentinstallmentaccounts
      # - pentius_currentlydelinquentrevolvingaccounts
      # - pentius_creditunionaccounts
      # - pentius_monthssincedelinquency
      # - pentius_creditcardutilization
      # - pentius_currentlydelinquentaccounts                          
      - dst_HH_INCOME
      - dst_CREDIT_RATING
      - dst_NET_WORTH
      - dst_HOME_MKT_VALUE
      - dst_EDUCATION
    date:
      - application_date