data_path:
  input: data\input\
  output: data\output\sample.csv

plot:
  x_label: home_ownership
  y_label: all_util
  z_label: application_date
  cmap: viridis
  title: Lendingclub Cluster Plot

cluster:
  kmeans:
    n_clusters: 3
    kwargs:
      init: random
      max_iter: 300
      random_state: 0

  hierarchical:
    n_clusters: 3
    kwargs:
      linkage: ward

  dbscan:
    eps: 0.5
    min_samples: 5
    kwargs:
      metric: euclidean

columns:
  index:
    - id
  label:
    - default
  features:
    categorical:
        - application_type
        - home_ownership
    high_categorical:
        - addr_state
    date:
        # - last_credit_pull_d
        # - issue_d
        - application_date
    numeric:
        - acc_now_delinq
        - acc_open_past_24mths
        - all_util
        - annual_inc
        - annual_inc_joint
        - avg_cur_bal
        - bc_open_to_buy
        - bc_util
        # - collections_12_mths_ex_med
        # - delinq_2yrs
        # - delinq_amnt
        - dti
        - dti_joint
        - emp_length
        - earliest_cr_line
        # - fico_range_low
        # - fico_range_high
        - fico_score
        - il_util
        - inq_fi
        - inq_last_12m
        - inq_last_6mths
        - max_bal_bc
        - mo_sin_old_il_acct
        - mo_sin_old_rev_tl_op
        - mo_sin_rcnt_rev_tl_op
        - mo_sin_rcnt_tl
        - mort_acc
        - mths_since_rcnt_il
        - mths_since_recent_bc
        - mths_since_recent_inq
        - num_accts_ever_120_pd
        - num_actv_bc_tl
        - num_actv_rev_tl
        - num_bc_sats
        - num_bc_tl
        - num_op_rev_tl
        - num_rev_accts
        - num_rev_tl_bal_gt_0
        - num_sats
        - num_tl_120dpd_2m
        - num_tl_30dpd
        - num_tl_90g_dpd_24m
        - num_tl_op_past_12m
        - open_acc
        - open_acc_6m
        - open_act_il
        - open_il_12m
        - open_il_24m
        - open_rv_12m
        - open_rv_24m
        - pct_tl_nvr_dlq
        - percent_bc_gt_75
        # - pub_rec_bankruptcies
        - revol_bal
        # - revol_bal_joint 
        - revol_util
        # - tot_coll_amt
        - tot_cur_bal
        - tot_hi_cred_lim
        - total_acc
        - total_bal_ex_mort
        - total_bal_il
        - total_bc_limit
        - total_cu_tl
        - total_il_high_credit_limit
        - total_rev_hi_lim
